sudo: required
dist: trusty

language: c

branches:
  only:
    - master

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - cmake -Duse_terminal=ON -Duse_sdl2=OFF .. && make

notifications:
  email: false
