sudo: required
dist: trusty

language: c

branches:
  only:
    - master

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-dev

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja python3-pip python3-dev build-essential
  - sudo pip3 install --upgrade pip
  - sudo pip3 install meson

script:
  - meson build -Dfrontend=terminal
  - cd build
  - ninja
  - mesonconf -Dfrontend=sdl
  - ninja
  - ninja test

notifications:
  email: false
